services:
    _defaults:
        autowire: true
        autoconfigure: true

    # DataFixtures 服务仅在测试环境可用
    Tourze\TrainTeacherBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']
        autoconfigure: true
        public: true