services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\TrainTeacherBundle\Command\:
    resource: '../../Command/'
  Tourze\TrainTeacherBundle\Repository\:
    resource: '../../Repository/'
  Tourze\TrainTeacherBundle\Service\:
    resource: '../../Service/'
