services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\TrainTeacherBundle\Command\:
    resource: '../../Command/'
  Tourze\TrainTeacherBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
  Tourze\TrainTeacherBundle\Repository\:
    resource: '../../Repository/'
  Tourze\TrainTeacherBundle\Helper\:
    resource: '../../Helper/'
  Tourze\TrainTeacherBundle\Service\EvaluationService:
  Tourze\TrainTeacherBundle\Service\PerformanceService:
  Tourze\TrainTeacherBundle\Service\TeacherService:
  Tourze\TrainTeacherBundle\Service\AdminMenu:
    public: true
    tags: ['tourze.easy_admin_menu.provider']
  Tourze\TrainTeacherBundle\EntityListener\:
    resource: '../../EntityListener/'
    tags: ['doctrine.orm.entity_listener']
